name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Verifica se houve alterações
          if [ -n "$(git status --porcelain)" ]; then
            git checkout -b release-update
            git add CHANGELOG.md public/patch-notes.json
            git commit -m "chore: update changelog and patch notes"
            git push --set-upstream origin release-update
            
            # Criar o pull request
            curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
              -d '{"title":"Release Update","body":"This pull request updates the changelog and patch notes.","head":"release-update","base":"main"}' \
              https://api.github.com/repos/${{ github.repository }}/pulls
          else
            echo "No changes to commit."
          fi
